name: Auto Build OpenWRT

on:

  workflow_dispatch:
            inputs:
              Models:
                description: 'Input Models Name'     
                required: true
                default: 'WR703N'
jobs:
  Build-OpenWrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation depends
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 zip unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
# SSH Connect To Actions
#      - name: Setup Debug Session
#        uses: csexton/debugger-action@master
        
      - name: Clone Source
        run: |
          cd /home/runner
          bash ${GITHUB_WORKSPACE}/${{github.event.inputs.Models}}/clone_source.sh
          sudo chown -R runner:runner OpenWRT
          
      - name: Before Build
        run: |
          /bin/bash ${GITHUB_WORKSPACE}/before_build.sh
          cp -fpR ${GITHUB_WORKSPACE}/${{github.event.inputs.Models}}/. /home/runner/OpenWRT/
          
      - name: Start Build
        run: | 
          cd /home/runner/OpenWRT
          mv .config .config_default
          rm -f .config.old
          config_names="$(ls .config*)"
          for i in $config_names;do mv -f $i .config; make defconfig; make -j$[$(nproc)+1] V=s; rm -rf build_dir/target* build_dir/toolchain* staging_dir/target* staging_dir/toolchain*; done
      
      - name: After Build
        run: |
          /bin/bash ${GITHUB_WORKSPACE}/after_build.sh
      
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.Models}}-Packages
          path: /home/runner/OpenWRT/bin/packages/
      
      - name: Upload Firmwares
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.Models}}-Firmwares
          path: /home/runner/OpenWRT/bin/targets/