name: Auto Build OpenWRT

on:
  workflow_dispatch:
            inputs:
              Models:
                description: 'Input Models Name'     
                required: true
                default: 'WR703N'
jobs:
  Build-OpenWrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation depends
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 zip unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
# SSH Connect To Actions
#      - name: Setup Debug Session
#        uses: csexton/debugger-action@master
        
      - name: Clone Source
        run: |
          cd ${GITHUB_WORKSPACE}/
          bash ${GITHUB_WORKSPACE}/${{github.event.inputs.Models}}/clone_source.sh
       
      - name: Start Build
        run: | 
          cd ${GITHUB_WORKSPACE}/OpenWRT
          bash ${GITHUB_WORKSPACE}/start_build.sh
          
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.Models}}-Packages
          path: /home/runner/OpenWRT/bin/packages/
      
      - name: Upload Firmwares
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.Models}}-Firmwares
          path: /home/runner/OpenWRT/bin/targets/